name: xenomake
channels:
    - bih-cubi
    - conda-forge
    - bioconda
    - defaults
    - numba
dependencies:
    - python>=3.10
    - snakemake>=5.32.0,<7.32.4
    - star>=2.7.1a
    - samtools>=1.13
    - sambamba>=0.6.8
    - pip>=21.1
    - pysam>=0.16.0.1
    - pot
    - openjdk==11.0.15
    - pigz
    - xengsort==2.0.1
    - pip:
        - pandas>=1.3.0,<=1.5.1
        - scanpy>=1.8.1
        - leidenalg>=0.8.1
        - numpy>=1.18.1
        - more-itertools>=8.7.0
        - biopython>=1.78
        - scipy>=1.5.0
        - scikit-misc>=0.1.3
        - scikit-learn>=0.23.1
        - pyyaml
        - pytest
        - zarr
        - numba>=0.56
        - jsonargparse>=4.24.0
        - h5py
        - cutadapt
